apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninja
  namespace: ninja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninja-app
  template:
    metadata:
      labels:
        app: ninja-app
    spec:
      containers:
      - name: n-cont
        image: ghcr.io/saisairepo/ninja:v1.0
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
      imagePullSecrets:
      - name: ninja-secret
---
apiVersion: v1
kind: Service
metadata:
  name: n-service
  namespace: ninja
spec:
  selector:
    app: ninja-app
  ports:
  - name: http
    port: 80
    targetPort: 3001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n-ingress
  namespace: ninja
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ninja.mlhuillier.com
      secretName: com-tls
  rules:
    - host: ninja.mlhuillier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n-service
                port:
                  number: 80
